name: Deploy to GitHub Pages

# Triggered on push to main branch
# Re-running after making repository public
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20.2'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Clear npm cache
        run: |
          npm cache clean --force

      - name: Install Dependencies
        run: |
          npm install --no-audit --no-fund --verbose --registry=https://registry.npmjs.org/ || (echo "npm install failed" && npm cache verify && exit 1)

      - name: Build
        run: |
          npm run build || (echo "npm build failed" && exit 1)

      - name: Deploy
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages 